apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: component-service-stock
  description: stock Service
spec:
  type: service
  lifecycle: production
  owner: tunas
  system: system-stock
  providesApis:
    - api-stock
  consumesApis:
    - api-products
  dependsOn:
    - resource:resource-db-stock
    - resource:resource-appservice-stock
    - resource:resource-topic-stock
    - resource:resource-subscription-stock-topic-products
    - component:component-library-common-host